const CertificateItems = [
  {
    name: 'Developer Certificate',
    icon: 'ri-code-s-slash-line',
    items: [
      {
        name: 'Belajar Membuat Aplikasi Back-End untuk Pemula dengan Google Cloud',
        publisher: 'Dicoding Academy',
        credential: '07Z64065WPQR',
        year: 'Oct 2024 - Oct 2027',
        ref: 'https://www.dicoding.com/certificates/07Z64065WPQR',
      },
      {
        name: 'Belajar Dasar AI',
        publisher: 'Dicoding Academy',
        credential: '81P24707YZOY',
        year: 'Oct 2024 - Oct 2027',
        ref: 'https://www.dicoding.com/certificates/81P24707YZOY',
      },
      {
        name: 'Pengenalan ke Logika Pemrograman (Programming Logic 101)',
        publisher: 'Dicoding Academy',
        credential: 'QLZ97MKM9P5D',
        year: 'Oct 2024 - Oct 2027',
        ref: 'https://www.dicoding.com/certificates/QLZ97MKM9P5D',
      },
      {
        name: 'Belajar Dasar Pemrograman Web',
        publisher: 'Dicoding Academy',
        credential: '4EXG7E6REPRL',
        year: 'Sep 2024 - Sep 2027',
        ref: 'https://www.dicoding.com/certificates/4EXG7E6REPRL',
      },
      {
        name: 'Belajar Dasar Pemrograman JavaScript',
        publisher: 'Dicoding Academy',
        credential: '4EXG7E6REPRL',
        year: 'Oct 2024 - Oct 2027',
        ref: 'https://www.dicoding.com/certificates/KEXLY06K0ZG2',
      },
      {
        name: ' Belajar Membuat Aplikasi Web dengan React',
        publisher: 'Dicoding Academy',
        credential: 'EYX4G15NJZDL',
        year: 'Jan 2025 - Jan 2028',
        ref: 'https://www.dicoding.com/certificates/07Z64065WPQR',
      },
      {
        name: 'MEMBUAT APLIKASI MOBILE EDUKASI (MAME)',
        publisher: 'Direktorat Jenderal Pendidikan Tinggi, Riset dan Teknologi Kemdikbudristek',
        credential: '2260/J6.3/TI/2021',
        year: 'September 2021',
        ref: '',
      },
      {
        name: 'IAII PROFISIENSI DATABASE SYSTEM',
        publisher: 'Ikatan Ahli Informatika Indonesia',
        credential: 'QyBIloydZG',
        year: 'Jul 2023',
        ref: '',
      },
      {
        name: 'Sertifikat Kelas Belajar Dasar HTML',
        publisher: 'Codepolitan',
        credential: 'WRDYSEJ',
        year: 'February 2024 - February 2027',
        ref: 'https://codepolitan.com/c/WRDYSEJ',
      },
      {
        name: 'Sertifikat Kelas Pengenalan Database Menggunakan MySQL',
        publisher: 'Codepolitan',
        credential: '8ZBFLHU',
        year: 'March 2024 - March 2027',
        ref: 'https://codepolitan.com/c/8ZBFLHU',
      },
      {
        name: 'Sertifikat Kelas Laravel 8x Fundamental',
        publisher: 'Codepolitan',
        credential: 'WQ6YAHC',
        year: 'March 2024 - March 2027',
        ref: 'https://codepolitan.com/c/WQ6YAHC',
      },
      {
        name: 'Sertifikat Kelas Konsep Dasar Pemrograman Berorientasi Objek di PHP',
        publisher: 'Codepolitan',
        credential: 'OBWK3WA',
        year: 'March 2024 - March 2027',
        ref: 'https://codepolitan.com/c/OBWK3WA',
      },
      {
        name: 'Sertifikat Kelas Belajar Pemrograman PHP',
        publisher: 'Codepolitan',
        credential: 'LVQJR9H',
        year: 'March 2024 - March 2027',
        ref: 'https://codepolitan.com/c/LVQJR9H',
      },
      {
        name: 'Sertifikat Kelas Belajar JavaScript',
        publisher: 'Codepolitan',
        credential: 'PZH2RUM',
        year: 'March 2024 - March 2027',
        ref: 'https://codepolitan.com/c/PZH2RUM',
      },
      {
        name: 'Sertifikat Kelas Belajar JQuery Dasar',
        publisher: 'Codepolitan',
        credential: '1GVBNFL',
        year: 'March 2024 - March 2027',
        ref: 'https://codepolitan.com/c/1GVBNFL',
      },
      {
        name: 'Sertifikat Kelas Belajar Framework Laravel Dasar',
        publisher: 'Codepolitan',
        credential: 'FUWLCAM',
        year: 'March 2024 - March 2027',
        ref: 'https://codepolitan.com/c/FUWLCAM',
      },
      {
        name: 'Sertifikat Kelas Belajar Dasar CSS',
        publisher: 'Codepolitan',
        credential: 'RPF3OHN',
        year: 'March 2024 - March 2027',
        ref: 'https://codepolitan.com/c/RPF3OHN',
      },
      {
        name: 'Sertifikat Kelas Belajar Bootstrap CSS Framework',
        publisher: 'Codepolitan',
        credential: 'XEPR9YL',
        year: 'March 2024 - March 2027',
        ref: 'https://codepolitan.com/c/XEPR9YL',
      },
      {
        name: 'Sertifikat Kelas Penggunaan Database MySQL pada Pemrograman PHP',
        publisher: 'Codepolitan',
        credential: '6BAGEU9',
        year: 'July 2024 - July 2027',
        ref: 'https://codepolitan.com/c/6BAGEU9',
      },
      {
        name: 'Sertifikat Kelas Panduan Awal Menjadi Fullstack Web Developer',
        publisher: 'Codepolitan',
        credential: 'TWXA4PN',
        year: 'July 2024 - July 2027',
        ref: 'https://codepolitan.com/c/TWXA4PN',
      },
      {
        name: 'Sertifikat Kelas Membuat Landing Page Website dengan Bootstrap 4',
        publisher: 'Codepolitan',
        credential: 'YWO2FBS',
        year: 'July 2024 - July 2027',
        ref: 'https://codepolitan.com/c/YWO2FBS',
      },
      {
        name: 'Skilvul SkilBadge - React Dasar',
        publisher: 'Skilvul',
        credential: '',
        year: 'Augst 2024',
        ref: '',
      },
    ],
  },
  {
    name: 'Cyber Security Certificate',
    icon: 'ri-bug-line',
    items: [
      {
        name: 'LKS WILKER 4 CYBER SECURITY Field',
        publisher: 'Direktorat Jenderal Pendidikan Tinggi, Riset dan Teknologi Kemdikbudristek',
        credential: '08/MKKS/Wilker4/II/2022',
        year: 'February 2021',
        ref: '',
      },
      {
        name: 'Sertifikat peserta Gemastik : Cyber Security',
        publisher: 'Direktorat Jenderal Pendidikan Tinggi, Riset dan Teknologi Kemdikbudristek',
        credential: '001/DIV 2/GXV/2022',
        year: 'November 2022',
        ref: '',
      },
      {
        name: 'Ethical Hacker-Jr Penetration Tester',
        publisher: 'Cisco Networking Academy',
        credential: '',
        year: '2024',
        ref: '',
      },
      {
        name: 'Foundations of Cybersecurity',
        publisher: 'Coursera Google',
        credential: 'UDGBA9VQ3ZSM',
        year: '2025',
        ref: 'https://coursera.org/share/6ffd1284538c86692d4030cffe66dc3c',
      },
      {
        name: 'Play It Safe: Manage Security Risks',
        publisher: 'Coursera Google',
        credential: 'VONG6QQ7FS4F',
        year: '2025',
        ref: 'https://coursera.org/share/479a6d8b821a7e06be657ad7d5456750',
      },
      {
        name: 'Connect and Protect: Networks and Network Security',
        publisher: 'Coursera Google',
        credential: 'C37XFKOX94DF',
        year: '2025',
        ref: 'https://coursera.org/share/2abf009d390bfd25a6d7ba67fa47a807',
      },
    ],
  },
  {
    name: 'Cloud Computing Certificate',
    icon: 'ri-cloud-line',
    items: [
      {
        name: 'Menjadi Google Cloud Architect',
        publisher: 'Dicoding Academy',
        credential: '53XEDE5V9PRN',
        year: 'Jan 2025 - Jan 2028',
        ref: 'https://www.dicoding.com/certificates/53XEDE5V9PRN',
      },
      {
        name: 'Google Cloud Computing Foundations Certificate',
        publisher: 'Google Cloud Skill Boost',
        credential: '0LZ0452O0P65',
        year: 'Nov 2024 - Nov 2029',
        ref: 'https://www.credly.com/badges/7e1302a4-4093-4818-b25d-d9f7d8a30a0d/public_url',
      },
      {
        name: 'Develop Your Google Cloud Network Skill Badge',
        publisher: 'Google Cloud Skill Boost',
        credential: '0LZ0452O0P65',
        year: 'Nov 2024 - Nov 2027',
        ref: 'https://www.credly.com/badges/c9a47783-7266-48ba-9222-9e2e6a2e2964/public_url',
      },
      {
        name: 'Prepare Data for ML APIs on Google Cloud Skill Badge',
        publisher: 'Google Cloud Skill Boost',
        credential: '0LZ0452O0P65',
        year: 'Nov 2024 - Nov 2027',
        ref: 'https://www.credly.com/badges/8ca61c4f-113b-45e9-ac08-e08360580804/public_url',
      },
      {
        name: 'Monitor and Log with Google Cloud Operations Suite Skill Badge',
        publisher: 'Google Cloud Skill Boost',
        credential: '0LZ0452O0P65',
        year: 'Nov 2024 - Nov 2027',
        ref: 'https://www.credly.com/badges/8ca61c4f-113b-45e9-ac08-e08360580804/public_url',
      },
      {
        name: 'Implement Load Balancing on Compute Engine Skill Badge',
        publisher: 'Google Cloud Skill Boost',
        credential: '0LZ0452O0P65',
        year: 'Nov 2024 - Nov 2027',
        ref: 'https://www.credly.com/badges/95d6ec86-bce4-4c03-ae07-cfcdbddc552b/public_url',
      },
      {
        name: 'Penerapan Machine Learning dengan Google Cloud',
        publisher: 'Dicoding Academy',
        credential: 'N9ZOY0E88PG5',
        year: 'Nov 2024 - Nov 2027',
        ref: 'https://www.dicoding.com/certificates/N9ZOY0E88PG5',
      },

      {
        name: 'Using OSS to Publish a Static Website',
        publisher: 'Alibaba Cloud',
        credential: 'ACFW240240500120518',
        year: 'May 2024 - May 2027',
        ref: '',
      },
      {
        name: 'Cloud platform security overview',
        publisher: 'Alibaba Cloud',
        credential: 'ACFS01240500120546',
        year: 'May 2024 - May 2027',
        ref: '',
      },
      {
        name: 'Internetworking with VPC - Cloud Certification ',
        publisher: 'Alibaba Cloud',
        credential: 'ACFC20240500120543',
        year: 'May 2024 - May 2027',
        ref: '',
      },
      {
        name: 'Handle Large Traffic with Load Balancer - Cloud Certification ',
        publisher: 'Alibaba Cloud',
        credential: 'ACFC06240500120545',
        year: 'Apr 2024 - Apr 2027',
        ref: '',
      },
      {
        name: 'Alibaba Cloud Network Solution',
        publisher: 'Alibaba Cloud',
        credential: 'ACFC51240500120528',
        year: 'May 2024 - May 2027',
        ref: '',
      },
      {
        name: 'Operate and Manage a Relational Database on the Cloud',
        publisher: 'Alibaba Cloud',
        credential: 'ACFC4240500120520',
        year: 'May 2024 - May 2027',
        ref: '',
      },
      {
        name: 'Manage and Operate MySQL Database',
        publisher: 'Alibaba Cloud',
        credential: 'ACFW238240400115460',
        year: 'April 2024 - April 2027',
        ref: '',
      },
      {
        name: 'Operate and Manage a Cloud Server',
        publisher: 'Alibaba Cloud',
        credential: 'ACFC03240400115447',
        year: 'April 2024 - April 2027',
        ref: '',
      },
      {
        name: 'Using ECS to Construct a Dynamic Website',
        publisher: 'Alibaba Cloud',
        credential: 'ACFW125240400115290',
        year: 'April 2024 - April 2027',
        ref: '',
      },
      {
        name: 'Network Series Courses',
        publisher: 'Alibaba Cloud',
        credential: 'ACFW237240400115450',
        year: 'Apr 2024 - Apr 2027',
        ref: '',
      },
      {
        name: 'Apsara Clouder - Cloud Certification ',
        publisher: 'Alibaba Cloud',
        credential: 'ACCD0119700100007511',
        year: 'Apr 2024 - Apr 2027',
        ref: '',
      },
      {
        name: 'ACA Cloud Certification',
        publisher: 'Alibaba Cloud',
        credential: 'IACA01240500120109L',
        year: 'May 2024 - May 2027',
        ref: '',
      },
      {
        name: 'ACP Cloud Computing Certification',
        publisher: 'Alibaba Cloud',
        credential: 'IACP01240600124394',
        year: 'June 2024 - June 2027',
        ref: 'https://edu.alibabacloud.com/clouder/my/clouderpackage/?type=acp&clouder_certificat_id=123064',
      },
    ],
  },
  {
    name: 'IT Support Certificate',
    icon: 'ri-computer-line',
    items: [
      {
        name: 'Certificate Of Competency Assessment TKJ',
        publisher: 'SMKN 1 DONOROJO',
        credential: '',
        year: '2022',
        ref: '',
      },
    ],
  },
  {
    name: 'Network Administrator Certificate',
    icon: 'ri-global-line',
    items: [
      {
        name: 'MTCNA',
        publisher: 'MikroTik',
        credential: '2104NA6671',
        year: 'April 2021',
        ref: '',
      },
      {
        name: 'JNA VSGA 2022',
        publisher: 'Digitalent Kominfo',
        credential: 'Mkjlsdhw122',
        year: 'November 2022',
        ref: '',
      },

      {
        name: 'Certificate Of Competency LSP Network Engineer',
        publisher: 'BNSP (Badan Nasional Sertifikasi Profesi)',
        credential: '61200 3513 3 0038849 2022',
        year: 'November 2022',
        ref: '',
      },
      {
        name: 'CCNA: Introduction to Networks',
        publisher: 'BNSP (Badan Nasional Sertifikasi Profesi)',
        credential: '61200 3513 3 0038849 2022',
        year: 'November 2024 - 2027',
        ref: 'https://www.credly.com/badges/a726d794-a37b-43b9-90d6-28d0e05ed940/public_url',
      },
    ],
  },
  {
    name: 'Other Certificate',
    icon: 'ri-more-fill',
    items: [
      {
        name: 'Bangkit Academy Certificate',
        publisher: '',
        credential: 'BA24/GRAD/XXIV-01/C193B4KY1049',
        year: '2024',
        ref: '',
      },
      {
        name: 'Seminar Wajib Entrepenur',
        publisher: 'Universitas Bina Sarana Informatika',
        credential: '',
        year: '2024',
        ref: '',
      },
      {
        name: 'Google Profil Bisnis dan E-Commerce (Digital Entrepreneurship Academy)',
        publisher: 'Digital Talent Scholarship',
        credential: '1966871850-165/DEA/BLSDM.Kominfo/2023',
        year: 'June 2023',
        ref: 'https://digitalent.kominfo.go.id/cek-sertifikat',
      },
      {
        name: 'Software Quality Assurance',
        publisher: 'Tanjung Mulia Informatika',
        credential: 'PT-TMI/WK-240719-SQA.G1-01',
        year: 'July 2023',
        ref: '',
      },
    ],
  },
];

export default CertificateItems;
